name: Backend EC2 Deployment

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > SPM-Backend.pem
          chmod 600 SPM-Backend.pem

      - name: Deploy to EC2
        run: |
          ssh -i "SPM-Backend.pem" -o StrictHostKeyChecking=no ubuntu@ec2-3-104-64-250.ap-southeast-2.compute.amazonaws.com << 'EOF'
            cd spm_
            git pull origin main  # Pull latest changes
            cd Backend
            npm install  # Install dependencies
            sudo systemctl restart myapp.service
            sudo systemctl restart caddy
          EOF